name: vyktor
description: Find video game competitions near you!

version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: '^0.14.0'
  cached_network_image: '^1.1.0'
  equatable: '^0.3.0'
  flutter_bloc: '^0.20.0'
  geolocator: '^5.1.0'
  google_maps_flutter: '^0.5.19+2'
  graphql: '^2.0.0'
  path_provider: '^0.5.0+1'
  permission_handler: '^3.2.0'
  shared_preferences: '^0.5.3+4'
  url_launcher: '^5.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.7.2+1'

flutter_icons:
  image_path: 'assets/images/icon-128x128.png'
  android: true

flutter:
  uses-material-design: true
